# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Common Acumen
email: commonacumen@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog site for you to follow my ideas and thoughts at blog.commonacumen.com
#twitter_username: username
github_username: commonacumen
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "CommonAcumen"
  avatar : "/assets/images/caLogo.jpg"
  bio    : "Please follow me at blog.commonacumen.com"
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-blog"
      url: "https://blog.commonacumen.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://www"
#    - label: "YouTube"
#      icon: "fab fa-fw fa-youtube"
#      url: "https://www.youtube.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/commonacumen/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://commonacumen.com/"
      

footer:
  links:
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://www.instagram.com/"
#    - label: "YouTube"
#      icon: "fab fa-fw fa-youtube"
#      url: "https://www.youtube.com/@"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/commonacumen/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
